### ISSUE TITLE
todo with una

### ISSUE THREAD

**Issue by willsheffler** [willsheffler/worms#4]
- [ ] new version of sublime w/better python syntax highlighting
- [ ] install yapf and the sublime plugin
- [ ] install that remember-code-folding plugin
